# Generated by Django 5.1.6 on 2025-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commune',
            field=models.CharField(default=1, max_length=100, verbose_name='البلدية'),
            preserve_default=False,
        ),
    ]
